- name: Install Postgres 14
  hosts: all
  tasks:
    - name: install the pgdg rpm from a remote repo
      become: yes
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm 
        state: present
    - name: install postgresql server
      become: yes
      yum:
          name: "{{ packages }}"
      vars:
          packages:
          - postgresql14-server
    - name: Create Postgres data directory
      become: yes
      file:
        path: "{{ postgres_data_dir }}"
        state: directory
        owner: postgres

    - name: Check if PGDATA is empty
      find:
        paths: "{{ postgres_data_dir }}"
        file_type: directory
        patterns: "*"
      register: dir_files

    - name: initialize postgresql cluster
      shell: /usr/pgsql-14/bin/initdb -k
      become: yes
      become_user: postgres
      when: dir_files.matched|int == 0
      environment:
        PGDATA: "{{ postgres_data_dir }}"
        LC_ALL: "en_US.UTF-8"
    - name: Modify Postgres 14 service to adapt pgdata
      become: yes
      file:
        path: /etc/systemd/system/postgresql-14.service.d
        state: directory
    - name: add systemd override
      become: yes
      template:
        src: templates/override.conf
        dest: /etc/systemd/system/postgresql-14.service.d/override.conf
    - name: starting Postgres 14
      become: yes
      systemd:
        daemon_reload: yes
        name: postgresql-14
        state: started
        enabled: yes

    - name: check if Postgres is ready
      shell: /usr/pgsql-14/bin/pg_isready --dbname=postgres --username=postgres
      register: pg_result
      failed_when: "'no response' in pg_result.stdout"
    - debug:
        var: pg_result
